---
- name: Deploy Node.js Application
  hosts: localhost
  connection: local
  become: true
  vars:
    app_dir: "/var/www/simple-nodejs-app"
    repo_url: "https://github.com/rhdixit2001/simple-nodejs-app.git"
    branch: "main"
  tasks:
    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes
