---
- name: Deploy Node.js Application
  hosts: localhost
  connection: local
  become: yes
  vars:
    app_dir: "/var/www/simple-nodejs-app"
    repo_url: "https://github.com/rhdixit2001/simple-nodejs-app.git"
    branch: "main"
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, World!"
